version: '3.7'
services:
  tracker:
    build: .
    restart: always
    ports:
      - 8081:8080
    environment:
      PORT: 8080
      BALANCE_PORT: 36581
      DATABASE_URL: 'postgres://SauerTracker:postgrespassword@postgres:5432'
      REDIS_URL: 'redis://redis'
      BASE_ELO: 1200
      MASTER_PORT: 28787
      MASTER_HOST: master.sauerbraten.org
      NODE_ENV: production
    entrypoint: './docker-entrypoint.sh'
    command: 'start'
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # - ./dump.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: SauerTracker
  redis:
    image: redis
    restart: always
